#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Downloads the Kapso OpenAPI documents into specs/ and records their provenance.

.DESCRIPTION
    The specs are vendored rather than fetched at build time so that a build is
    reproducible and works offline, and so that a change to Kapso's contract shows
    up as a reviewable diff instead of as a surprise at runtime.

    provenance.json records the URL and SHA-256 of every document, including the
    ones we deliberately do not generate from. See the "watched" entries below.

.PARAMETER Check
    Downloads into a temporary directory and compares against what is committed,
    without modifying specs/. Exits non-zero when they differ. Used by CI to
    detect upstream drift.

.EXAMPLE
    pwsh eng/Sync-Specs.ps1
    pwsh eng/Sync-Specs.ps1 -Check
#>
[CmdletBinding()]
param(
    [switch] $Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$specsDir = Join-Path $PSScriptRoot '..' 'specs' | Resolve-Path | Select-Object -ExpandProperty Path

# 'generate' documents produce clients. 'watch' documents are tracked only so we
# notice when they change.
#
# openapi-platform-new.yaml is watched rather than generated: it describes live
# endpoints (/db, /integrations) but is absent from Kapso's published docs
# navigation, and it disagrees with openapi-platform.yaml on 16 shared paths and
# 17 shared schemas. Merging would mean guessing which definition is current, and
# guessing wrong yields wrong types that still compile. Revisit when Kapso
# documents it.
$documents = @(
    @{ Name = 'openapi-whatsapp.yaml';     Mode = 'generate'; Url = 'https://docs.kapso.ai/api/meta/whatsapp/openapi-whatsapp.yaml' }
    @{ Name = 'openapi-platform.yaml';     Mode = 'generate'; Url = 'https://docs.kapso.ai/api/platform/v1/openapi-platform.yaml' }
    @{ Name = 'openapi-workflows.yaml';    Mode = 'generate'; Url = 'https://docs.kapso.ai/api/platform/v1/openapi-workflows.yaml' }
    @{ Name = 'openapi-kapso-agent.yaml';  Mode = 'generate'; Url = 'https://docs.kapso.ai/api/platform/v1/openapi-kapso-agent.yaml' }
    @{ Name = 'openapi-platform-new.yaml'; Mode = 'watch';    Url = 'https://docs.kapso.ai/api/platform/v1/openapi-platform-new.yaml' }
)

$workDir = if ($Check) { Join-Path ([System.IO.Path]::GetTempPath()) "kapso-specs-$([guid]::NewGuid().ToString('N'))" } else { $specsDir }
if (-not (Test-Path $workDir)) { New-Item -ItemType Directory -Path $workDir -Force | Out-Null }

$previous = @{}
$provenancePath = Join-Path $specsDir 'provenance.json'
if (Test-Path $provenancePath) {
    foreach ($entry in (Get-Content $provenancePath -Raw | ConvertFrom-Json).documents) {
        $previous[$entry.name] = $entry.sha256
    }
}

$records = [System.Collections.Generic.List[object]]::new()
$drifted = [System.Collections.Generic.List[string]]::new()

foreach ($doc in $documents) {
    $target = Join-Path $workDir $doc.Name
    Write-Host "  fetching $($doc.Name)" -NoNewline

    Invoke-WebRequest -Uri $doc.Url -OutFile $target -MaximumRedirection 5 | Out-Null

    # Normalize to LF so the committed bytes, and therefore the hash, do not
    # depend on the machine that ran the sync.
    $text = [System.IO.File]::ReadAllText($target) -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText($target, $text)

    $hash = (Get-FileHash -Path $target -Algorithm SHA256).Hash.ToLowerInvariant()
    $known = if ($previous.ContainsKey($doc.Name)) { $previous[$doc.Name] } else { $null }

    if ($null -eq $known) {
        Write-Host "  new" -ForegroundColor Cyan
    }
    elseif ($known -ne $hash) {
        Write-Host "  CHANGED" -ForegroundColor Yellow
        $drifted.Add($doc.Name)
    }
    else {
        Write-Host "  unchanged" -ForegroundColor DarkGray
    }

    $records.Add([ordered]@{
        name   = $doc.Name
        url    = $doc.Url
        mode   = $doc.Mode
        sha256 = $hash
        bytes  = (Get-Item $target).Length
    })

    # A watched document is tracked by hash only. Committing a spec we do not
    # generate from would imply it is part of the contract.
    if ($doc.Mode -eq 'watch') { Remove-Item $target -Force }
}

if ($Check) {
    Remove-Item $workDir -Recurse -Force
    if ($drifted.Count -gt 0) {
        Write-Host ''
        Write-Host "Upstream specs changed: $($drifted -join ', ')" -ForegroundColor Yellow
        Write-Host 'Run: pwsh eng/Sync-Specs.ps1 && pwsh eng/Generate-Clients.ps1'
        exit 1
    }
    Write-Host ''
    Write-Host 'No drift.' -ForegroundColor Green
    exit 0
}

$provenance = [ordered]@{
    '$comment'  = 'Generated by eng/Sync-Specs.ps1. Do not edit by hand.'
    retrievedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    documents   = $records
}
$json = ($provenance | ConvertTo-Json -Depth 5).Replace("`r`n", "`n")
[System.IO.File]::WriteAllText($provenancePath, $json + "`n")

Write-Host ''
Write-Host "Wrote $provenancePath" -ForegroundColor Green
if ($drifted.Count -gt 0) {
    Write-Host "Regenerate the clients: pwsh eng/Generate-Clients.ps1" -ForegroundColor Yellow
}
