#!/usr/bin/env python3
"""Writes sample-document.pdf.

A PDF is generated rather than committed blind so the bytes are auditable: this
file is the whole definition of what gets sent. It is also why there is no
dependency on a PDF library for a one-page document.

The only fiddly part is the cross-reference table, which stores the byte offset
of every object, so the offsets are measured while the objects are appended
rather than guessed.

    python make-pdf.py
"""

from pathlib import Path

LINES = [
    (72, 780, 18, "Kapso .NET client"),
    (72, 750, 11, "Sample document, sent over the WhatsApp Cloud API."),
    (72, 726, 11, "Uploaded with KapsoMediaExtensions.UploadFileAsync, then sent"),
    (72, 710, 11, "as a document message referencing the returned media ID."),
    (72, 672, 9, "Generated by samples/Kapso.Samples.SendMedia/assets/make-pdf.py"),
]


def escape(text: str) -> str:
    """Backslash, and both parentheses, are special inside a PDF string."""
    return text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")


def build() -> bytes:
    content = "BT\n" + "".join(
        f"/F1 {size} Tf 1 0 0 1 {x} {y} Tm ({escape(text)}) Tj\n"
        for x, y, size, text in LINES
    ) + "ET"
    stream = content.encode("ascii")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
        b"/Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(stream)).encode() + b" >>\nstream\n" + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = []

    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + body + b"\nendobj\n"

    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()

    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_at}\n%%EOF\n"
    ).encode()

    return bytes(out)


if __name__ == "__main__":
    target = Path(__file__).with_name("sample-document.pdf")
    target.write_bytes(build())
    print(f"wrote {target.name} ({target.stat().st_size:,} bytes)")
